const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('paperdesk', {
  getSettings: () => ipcRenderer.invoke('get-settings'),
  setSettings: (settings) => ipcRenderer.invoke('set-settings', settings),
  listSources: () => ipcRenderer.invoke('list-sources'),
  addSource: (source) => ipcRenderer.invoke('add-source', source),
  removeSource: (id) => ipcRenderer.invoke('remove-source', id),
  pickSource: (type) => ipcRenderer.invoke('pick-source', type),
  scanSources: () => ipcRenderer.invoke('scan-sources'),
  listPapers: (query) => ipcRenderer.invoke('list-papers', query),
  getPaper: (id) => ipcRenderer.invoke('get-paper', id),
  upsertPaper: (paper) => ipcRenderer.invoke('upsert-paper', paper),
  deletePaper: (id) => ipcRenderer.invoke('delete-paper', id),
  openFile: (filePath) => ipcRenderer.invoke('open-file', filePath),
  openFolder: (filePath) => ipcRenderer.invoke('open-folder', filePath),
  onScanProgress: (callback) => ipcRenderer.on('scan-progress', (_, data) => callback(data)),
  getStats: (payload) => ipcRenderer.invoke('get-stats', payload),
  exportClassified: (payload) => ipcRenderer.invoke('export-classified', payload),
  llmRank: (payload) => ipcRenderer.invoke('llm-rank', payload),
  aiRecallSearch: (payload) => ipcRenderer.invoke('ai-recall-search', payload),
  ollamaPing: () => ipcRenderer.invoke('ollama-ping'),
  ollamaExtract: (payload) => ipcRenderer.invoke('ollama-extract-metadata', payload),
  ollamaSummarize: (payload) => ipcRenderer.invoke('ollama-summarize', payload),
  modelParseQuery: (payload) => ipcRenderer.invoke('model-parse-query', payload),
  translatePaper: (payload) => ipcRenderer.invoke('translate-paper', payload),
  extractAllMetadata: (payload) => ipcRenderer.invoke('extract-all-metadata', payload),
  rollbackExtract: () => ipcRenderer.invoke('rollback-extract'),
  onExtractProgress: (callback) => ipcRenderer.on('extract-progress', (_, data) => callback(data)),
  bulkTag: (payload) => ipcRenderer.invoke('bulk-tag', payload),
  bulkExport: (payload) => ipcRenderer.invoke('bulk-export', payload),
  exportPdf: (payload) => ipcRenderer.invoke('export-pdf', payload),
  exportCitation: (payload) => ipcRenderer.invoke('export-citation', payload),
  exportByFilter: (payload) => ipcRenderer.invoke('export-by-filter', payload),
  summarizeBatch: (payload) => ipcRenderer.invoke('summarize-batch', payload),
  findSimilar: (payload) => ipcRenderer.invoke('find-similar', payload),
  ensureEmbedding: (payload) => ipcRenderer.invoke('ensure-embedding', payload),
  listIgnoreRules: () => ipcRenderer.invoke('list-ignore-rules'),
  addIgnoreRule: (pattern) => ipcRenderer.invoke('add-ignore-rule', pattern),
  removeIgnoreRule: (id) => ipcRenderer.invoke('remove-ignore-rule', id),
  listSavedSearches: () => ipcRenderer.invoke('list-saved-searches'),
  addSavedSearch: (payload) => ipcRenderer.invoke('add-saved-search', payload),
  removeSavedSearch: (id) => ipcRenderer.invoke('remove-saved-search', id)
});
